
create table if not exists users
(
    id bigint generated by default as identity primary key,
    email      varchar(255),
    first_name varchar(255),
    image      varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       varchar(255)
);

create table if not exists abs
(
    id bigint generated by default as identity primary key,
    image   varchar(255),
    price   integer,
    title   varchar(255),
    user_id bigint constraint userId references users
);

create table if not exists comment
(
    id bigint generated by default as identity primary key,
    created_at integer,
    text       varchar(255),
    ads_id bigint constraint absId references abs,
    user_id bigint constraint uaserId references users
);
