
create table if not exists users
(
    id integer generated by default as identity primary key,
    email      varchar(255) unique,
    first_name varchar(255),
    image      varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       varchar(255)
);

create table if not exists ads
(
    pk integer generated by default as identity primary key,
    image   varchar(255),
    price   integer,
    title   varchar(255),
    users_id integer constraint userId references users
);

create table if not exists comment
(
    pk integer generated by default as identity primary key,
    created_at timestamp,
    text       varchar(255),
    ads_pk integer constraint absId references ads,
    users_id integer constraint uasersId references users
);

create table if not exists avatar
(
    id integer not null  primary key  constraint user_id  references users,
    file_path  varchar(255),
    file_size  bigint,
    media_type varchar(255)
);

create table if not exists picture
(
    id integer not null  primary key  constraint ads_id  references ads,
    file_path  varchar(255),
    file_size  bigint,
    media_type varchar(255)
);