

create table if not exists users (

    id          integer generated by default as identity primary key,
    email       varchar(255) not null constraint emailUnique unique,
    first_name  varchar(255) not null,
    image       varchar(255),
    last_name   varchar(255) not null,
    password    varchar(255) not null,
    phone       varchar(255) not null constraint phoneUnique unique,
    role        varchar(255)

);

GO

