
create table if not exists ads (

    id          integer generated by default as identity primary key,
    description varchar(255) not null constraint descrUnique unique,
    image       varchar(255),
    price       integer not null,
    title       varchar(255) not null constraint titleUnique unique,
    users_id    integer constraint adsUsersId references users

);

GO